#!/bin/bash
if [ $# -ne 1 ]; then
    echo "指定された引数は$#個だったので、!"
    echo "少なくとも１つの引数を指定してね"
    exit 1
fi
    arg=$1
    echo '引数は'${arg}'だよね？'
    echo '組み合わせた文字列を綴るよ'
    path1='~/prog/src/${arg}/boot.asm'
    path1=$(eval echo ${path1})
    path2='~/prog/src/${arg}/boot.img'
    path2=$(eval echo ${path2})
    path3='~/prog/src/${arg}/boot.lst'
    path3=$(eval echo ${path3})

    for var in path1 path2 path3
    do
        echo ${!var}
    done
    eval nasm ${path1} -o ${path2} -l ${path3}


    exit 0
